name: CI - Integration and E2E Tests

on: [pull_request]

jobs:
  run-int-e2e-tests:
    name: Run Integration and E2E Tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: bitnami/postgresql
        ports:
          - 5432:5432
        env:
          POSTGRESQL_USERNAME: postgres
          POSTGRESQL_PASSWORD: docker
          POSTGRESQL_DATABASE: projectdb

    # definir os passos necessarios para baixar o app e rodar os testes
    steps:
      - uses: actions/checkout@v3     # baixar o codigo do app no ubuntu

      - uses: actions/setup-node@v3   # configurar o Nodejs
        with:
          node-version: 18
          cache: 'npm'

      - run: npm ci  # instalar as dependencias sem interacao

      - run: npx prisma generate --schema ./src/shared/infrastructure/database/prisma/schema.prisma
        env:
          DATABASE_URL: "postgresql://postgres:docker@localhost:5432/projectdb?schema=public"

      - run: npm run test:int
        env:
          PORT: 3000
          NODE_ENV: test
          JWT_SECRET: fake_secret
          JWT_EXPIRES_IN: 86400
          DATABASE_URL: "postgresql://postgres:docker@localhost:5432/projectdb?schema=public"

      - run: npm run test:e2e
        env:
          PORT: 3000
          NODE_ENV: test
          JWT_SECRET: fake_secret
          JWT_EXPIRES_IN: 86400
          DATABASE_URL: "postgresql://postgres:docker@localhost:5432/projectdb?schema=public"
